### ISSUE TITLE
import * as lib from "lib" 

### ISSUE THREAD

**Issue by 0x-genesys** [urbanclap-engg/smart-docs-parser#1]
please change imports to

` import * as lib from "lib" `

from

` import lib from "lib" `

Problem: 

running 

`tsc file.ts`

throws error: 

``` 

src/document-parser/pan-parser.ts:2:8 - error TS1259: Module '"/Users/srdevl103/Workspace/springrole/external/smart-docs-parser/node_modules/moment/moment"' can only be default-imported using the 'esModuleInterop' flag

2 import moment from "moment";
         ~~~~~~

  node_modules/moment/moment.d.ts:736:1
    736 export = moment;
        ~~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.


```

this is because of imports done like in typescript:

`import thing from 'thing'; `

converts js like:

```
const thing_1 = require("thing");

thing_1.default.functionOnThing();
```

where the importing lib (loadash bluebird etc) don't have a default parameter.

reference : https://stackoverflow.com/questions/41148057/why-is-typescript-adding-default-to-a-globally-defined-import

**Comment by SourabhJaz** [comment]
@0x-genesys Typescripts __importDefault already handles it.

`var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
`

https://stackoverflow.com/questions/51725905/in-typescript-why-is-there-a-difference-between-typing-tsc-and-tsc-filename

`tsc filename` runs with default settings and not with that of `tsconfig.json`. That's the reason it didn't affect the actual build process nor the performance of library. 

Although have made the changes so that you can compile the single file as well (moment doesn't have a default export unlike Lodash and Bluebird) but please prefer using the `tsconfig.json` settings.
